work/urls.py
from django.urls import path
from .views import (Home, AdminControl, RegistrationView, AgricLoan, 
			BusinessLoan, AssestLoan, Login,ChoiceField,Grants,
			Investment,Logout,BeginnerInvest,Profile,PromoInvest,FinaleInvest,
			BeginnerPanel,PromoPanel,FinalePanel,DepositPanel,WithdrawalPanel,
			AboutUs) 
from django.views.generic import ListView
from django.contrib.auth import views as auth_views
# from . views import *
	

app_name = 'work'
urlpatterns =[ 
path(r'', Home, name='home'),
path(r'user_investment_profile', Profile, name='profile'),
path(r'oga_controller', AdminControl, name='ogacontrol'),
path(r'agricultural_grant', AgricLoan, name='agric'),
path(r'business_grant', BusinessLoan, name='business'),
path(r'assest_grant', AssestLoan, name='assest'),
path(r'register', RegistrationView, name='register'),
path(r'login', Login, name='login'),
path(r'about_us', AboutUs, name='about'),
path(r'make_your_choice', ChoiceField, name='choice'),
path(r'grant', Grants, name='grant'),
path(r'investment', Investment, name='investment'),
path(r'beginner_investment', BeginnerInvest, name='begin'),
path(r'promo_investment', PromoInvest, name='promo'),
path(r'finale_investment', FinaleInvest, name='finale'),
path(r'begin_panel/<int:id>', BeginnerPanel, name='begin_panel'),
path(r'promo_panel/<int:id>', PromoPanel, name='promo_panel'),
path(r'finale_panel/<int:id>', FinalePanel, name='finale_panel'),
path(r'deposit_panel/<int:id>', DepositPanel, name='deposit_panel'),
path(r'withdrawal_panel/<int:id>', WithdrawalPanel, name='withdrawal_panel'),
path(r'logout', Logout, name='logout'),


]

work/models.py
from django.db import models
import random
from django.utils import timezone
# import datetime
from datetime import datetime
from django.conf import settings
from .utils import generate_ref_code
from django.contrib.auth.models import User

CHOICES = [
	('Select Coin','Select Coin'),
	('Bitcoin','Bitcoin'),
	('Ethurum','Ethurum'),
	('Litcoin','Litcoin'),
	]

STATUS = [
	('Pending','Pending'),
	('Processing','Processing'),
	('Approved','Approved'),
	]

# Create your models here.

class Referal (models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="referrals")
	code = models.CharField(max_length=12, blank=True)
	recommeded_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True, related_name="referred_by")
	updated = models.DateTimeField(auto_now=True)
	created = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return f"{self.user.username}"

	def get_recommended_profiles(self):
		query = Referal.objects.all()
		my_rec = [ur for ur in query if ur.recommeded_by == self.user]
		return my_rec


	def save(self, *args, **kwargs):
		if self.code == "":
			code = generate_ref_code()
			self.code = code
		super().save(*args, **kwargs)


class AgricGrant(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	amount = models.IntegerField()
	message = models.TextField(blank=True, null=True)
	status = models.CharField(max_length=100, choices=STATUS, default='Pending')
	created = models.DateTimeField(auto_now=True)
	def __str__(self):
		return self.user.username


class BusinessGrant(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	amount = models.IntegerField()
	message = models.TextField(blank=True, null=True)
	status = models.CharField(max_length=100, choices=STATUS, default='Pending')
	created = models.DateTimeField(auto_now=True)
	def __str__(self):
		return self.user.username


class AssestGrant(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	amount = models.IntegerField()
	message = models.TextField(blank=True, null=True)
	status = models.CharField(max_length=100, choices=STATUS, default='Pending')
	created = models.DateTimeField(auto_now=True)
	def __str__(self):
		return self.user.username


class InvestBeginner(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	amount = models.IntegerField()
	status = models.CharField(max_length=100, choices=STATUS, default='Pending')
	late_updated = models.DateTimeField(auto_now=True)
	def __str__(self):
		return self.user.username

	def beginner_amount (self):
		return self.amount * 5 /100 + self.amount


class InvestPromo(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	amount = models.IntegerField()
	status = models.CharField(max_length=100, choices=STATUS, default='Pending')
	late_updated = models.DateTimeField(auto_now=True)
	def __str__(self):
		return self.user.username

	def promo_amount(self):
		return self.amount * 10 /100 + self.amount


class InvestFinale(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	amount = models.IntegerField()
	status = models.CharField(max_length=100, choices=STATUS, default='Pending')
	late_updated = models.DateTimeField(auto_now=True)
	def __str__(self):
		return self.user.username

	def finale_amount(self):
		return self.amount * 15 /100 + self.amount


class Withdrawal(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	address = models.CharField(max_length=200)
	coin = models.CharField(max_length=100, choices=CHOICES, default='Select Coin')
	amount = models.IntegerField()
	status = models.CharField(max_length=100, choices=STATUS, default='Pending')
	def __str__(self):
		return self.user.username


class Deposit(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	coin = models.CharField(max_length=100, choices=CHOICES, default='Select Coin')
	amount = models.IntegerField()
	status = models.CharField(max_length=100, choices=STATUS, default='Pending')
	def __str__(self):
		return self.user.username



work/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from .models import (AgricGrant, BusinessGrant, AssestGrant, InvestBeginner,
	Deposit, Withdrawal,InvestPromo,InvestFinale)
from django.db import transaction

from django.forms import TextInput



class AgricForm(forms.ModelForm):
    class Meta:
        model = AgricGrant
        fields =["message","amount", "status"]

        def save(self, **kwargs):
        	user = kwargs.pop('user')
        	instance = super(AgricGrant, self).save(**kwargs)
        	instance.user = AgricGrant.objects.get(user=user) 
        	instance.save()
        	return instance

class BusinessForm(forms.ModelForm):
    class Meta:
        model = BusinessGrant
        fields =["message","amount", "status"]

        def save(self, **kwargs):
        	user = kwargs.pop('user')
        	instance = super(AgricGrant, self).save(**kwargs)
        	instance.user = AgricGrant.objects.get(user=user) 
        	instance.save()
        	return instance



class AssestForm(forms.ModelForm):
    class Meta:
        model = AssestGrant
        fields =["message","amount", "status"]

        def save(self, **kwargs):
        	user = kwargs.pop('user')
        	instance = super(AgricGrant, self).save(**kwargs)
        	instance.user = AgricGrant.objects.get(user=user) 
        	instance.save()
        	return instance


class BeginnerForm(forms.ModelForm):
    class Meta:
        model = InvestBeginner
        fields =["amount", "status"]

        def save(self, **kwargs):
        	user = kwargs.pop('user')
        	instance = super(InvestBeginner, self).save(**kwargs)
        	instance.user = InvestBeginner.objects.get(user=user) 
        	instance.save()
        	return instance

class PromoForm(forms.ModelForm):
    class Meta:
        model = InvestPromo
        fields =["amount", "status"]

        def save(self, **kwargs):
            user = kwargs.pop('user')
            instance = super(InvestPromo, self).save(**kwargs)
            instance.user = InvestPromo.objects.get(user=user) 
            instance.save()
            return instance

class FinaleForm(forms.ModelForm):
    class Meta:
        model = InvestFinale
        fields =["amount", "status"]

        def save(self, **kwargs):
            user = kwargs.pop('user')
            instance = super(InvestFinale, self).save(**kwargs)
            instance.user = InvestFinale.objects.get(user=user) 
            instance.save()
            return instance


class SignUpForm(UserCreationForm):
	email = forms.EmailField()
	first_name = forms.CharField(max_length=60)
	last_name = forms.CharField(max_length=60)

	class Meta:
		model = User
		fields = ['username','first_name', 'last_name', 'email', 'password1', 'password2']


class LoginForm(AuthenticationForm):
	remember_me = forms.BooleanField(required=False)



class WithdrawForm(forms.ModelForm):
    class Meta:
        model = Withdrawal
        fields =["amount","address","coin", "status"]

        def save(self, **kwargs):
            user = kwargs.pop('user')
            instance = super(Withdrawal, self).save(**kwargs)
            instance.user = Withdrawal.objects.get(user=user) 
            instance.save()
            return instance

class DepositForm(forms.ModelForm):
    class Meta:
        model = Deposit
        fields =["amount","coin", "status"]

        def save(self, **kwargs):
            user = kwargs.pop('user')
            instance = super(Deposit, self).save(**kwargs)
            instance.user = Deposit.objects.get(user=user) 
            instance.save()
            return instance

class EmailForm(forms.Form):
    first_name = forms.CharField(max_length=60)
    last_name = forms.CharField(max_length=60)
    phone = forms.CharField(widget=TextInput(attrs={'type':'number'}))
    email = forms.EmailField()
    message = forms.CharField(widget=forms.Textarea)

class AdminEmail(forms.Form):
    name = forms.CharField(max_length=60)
    email = forms.EmailField()
    message = forms.CharField(widget=forms.Textarea)

work/templates/folder/assest_loan.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Wilder Loans & Investment</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'fontawesome/css/all.min.css' %}">

<style>

	section {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            min-height: 120vh;
        }

	.form-container {
           background: #fff;
           padding: 20px;
           border-radius: 10px;
           box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
           width: 100%;
           max-width: 500px;
        }
        .form-container h2 {
            margin-bottom: 20px;
            font-size: 24px;
            text-align: center;
        }
        .form-container label {
            display: block;
            margin-bottom: 5px;
            font-weight: bold;
        }
        .form-container input, .form-container textarea {
            width: 100%;
            padding: 10px;
            margin-bottom: 20px;
            border: 1px solid #ccc;
            border-radius: 5px;
        }
        .form-container button {
            width: 100%;
            padding: 10px;
            background-color: #28a745;
            color: #fff;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            font-size: 16px;
        }
        .form-container button:hover {
            background-color: #218838;
        }

        #id_status{
        	display: none;
        }
</style>
</head>

<body>
<!-- Header section -->
<header class="header">
	<a href="#" class="logo"><i class="fa fa-bank"></i> Wiilder Loans & Investment</a>
	
	
</header>

<section>

	<div class="form-container">
         {% if messages %}
        {% for message in messages %}
      <div class="alert alert-{{message.tag}}">{{message}}</div>
        {% endfor %}
        {% endif %}
        <h2 style="color:black">Valuable reasons for assest grants and amount needed.</h2>
        <p style="color:black; font-size: 1.3rem;"><b>Note:</b> You'll be assigned to our supervisory expert once your business plan is approved after working three days. thanks!!!  </p>
        <form action="" method="POST">
        	{% csrf_token %}
            {{form.errors}}
            <label for="name">Your Business Plan</label>
            {{form.message}}
            
            <label for="email">Grant Required</label>
            {{form.amount}}
            
            <label for="message">Status</label>
            {{form.status}}
            
            <button type="submit">Send</button>
        </form>
    </div>
</section>

<!-- footer section -->
<footer class="footer">
	<div class="footer-text">
		<p>Creating an environment for the rich and poor</p>
	</div>

	<div class="footer-IconTop">
		<a href="#home"><i class="fa-solid fa-angle-up"></i></a>
	</div>
	
</footer>

<script src="{% static 'js/jquery.js' %}"></script>
<script type="text/javascript">

    setTimeout(fade_out, 2000)
      function fade_out(){
        $(".alert").fadeOut().empty()
      };

    $("#id_amount").attr("placeholder", "Type the amount needed..");
    $("#id_message").attr("placeholder", "Tell us why you need a housing/assest grant..");

    
	let menuIcon  = document.querySelector("#menu-icon");
	let navbar  = document.querySelector(".navbar");

	menuIcon.onclick = () => {
		menuIcon.classList.toggle("fa-xmark")
		navbar.classList.toggle('active')
	}

	let sections = document.querySelectorAll('section');
	let navLinks = document.querySelectorAll('header nav a');

	window.onscroll = () =>{
		sections.forEach(sec=>{
			let top = window.scrollv;
			let offset = secoffsetTop = 150
			let height = sec.offsetHeight;
			let id = sec.getAttribute('id')

			if(top >= offset && top < offset + height){
				navLinks.forEach.apply(links =>{
					links.classList.remove("active");
					document.querySelector("header nav a(href*="+ id + ")").classList.add('active')
				});
			};
		});



		let header = document.querySelector('header');
		header.classList.toggle('sticky', window.scrollv > 100);


		menuIcon.classList.remove('fa-xmark');
		navbar.classList.remove('active');
	}

    

</script>
</body>

</html>

work/templates/folder/choice.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Wilder Loans & Investment</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'fontawesome/css/all.min.css' %}">
</head>

<body>
<!-- Header section -->
<header class="header">
	<a href="#" class="logo"><i class="fa fa-bank"></i> Wiilder Loans & Investment</a>
	
	
</header>
<!-- Header section ends -->

<!-- home section -->

<!-- loans section -->
<section class="loans" id="loans">
	<h2 class="heading">Choose your Motive</h2>
	<div class="loans-container">
		<div class="loans-box">
			<i class="fas fa-bank"></i>
			<h3>Loans</h3>
			<p>All loans are basically offered to potential client to start their various businesses and start earning</p>
			<a href="{% url 'work:grant' %}" class="btn">Loan</a>
		</div>

		<div class="loans-box">
			<i class="fas fa-bank"></i>
			<h3>Investment</h3>
			<p>Agricultural loan is basically loans offered to potential farmers to start farming and start earning</p>
			<a href="{% url 'work:profile' %}" class="btn">Investment</a>
		</div>
	
</section>
<!-- loans section ends -->





<!-- footer section -->
<footer class="footer">
	<div class="footer-text">
		<p>Creating an environment for the rich and poor</p>
	</div>

	<div class="footer-IconTop">
		<a href="#home"><i class="fa-solid fa-angle-up"></i></a>
	</div>
	
</footer>

<script src="{% static 'js/jquery.js' %}"></script>
<script type="text/javascript">
	let menuIcon  = document.querySelector("#menu-icon");
	let navbar  = document.querySelector(".navbar");

	menuIcon.onclick = () => {
		menuIcon.classList.toggle("fa-xmark")
		navbar.classList.toggle('active')
	}

	let sections = document.querySelectorAll('section');
	let navLinks = document.querySelectorAll('header nav a');

	window.onscroll = () =>{
		sections.forEach(sec=>{
			let top = window.scrollv;
			let offset = secoffsetTop = 150
			let height = sec.offsetHeight;
			let id = sec.getAttribute('id')

			if(top >= offset && top < offset + height){
				navLinks.forEach.apply(links =>{
					links.classList.remove("active");
					document.querySelector("header nav a(href*="+ id + ")").classList.add('active')
				});
			};
		});



		let header = document.querySelector('header');
		header.classList.toggle('sticky', window.scrollv > 100);


		menuIcon.classList.remove('fa-xmark');
		navbar.classList.remove('active');
	}
</script>
</body>

</html>

work/templates/folder/home.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Wilder Loans & Investment</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'fontawesome/css/all.min.css' %}">
</head>

<body>
<!-- Header section -->
<header class="header">
	<a href="#" class="logo"><i class="fa fa-bank"></i> Wilder Grants & Investment</a>
	<i class="fas fa-bars" id="menu-icon"></i>
	<nav class="navbar">
		<a href="#home" class="active">Home</a>
		<a href="#about">Abous Us</a>
		<a href="#loans">Loans</a>
		<a href="#investment">Investment</a>
		<a href="#testimonies">Testimonies</a>
		<a href="#contact">Contact Us</a>
	</nav>
	
</header>
<!-- Header section ends -->

<!-- home section -->
<section class="home" id=home>
	<div class="home-content">
		<h1>Wilder</h1>
		<h1>Loans and Investment</h1>
		<p>Creating an environment for the rich and poor</p><br>
	
	{% if request.user.is_authenticated %}
	<div class="">
		<div><a href="#" style="color:white; font-size:1.5rem"> Welcome {{request.user.first_name}} {{request.user.last_name}}</a></div><br>
		<a href="{% url 'work:logout' %}" class="btn"> Logout</a>
		
		</div>
		

		{% else %}
		<div class="loginRegister">
		<a href="{% url 'work:register' %}" class="btn"> Register</a>
		<a href="{% url 'work:login' %}" class="btn">Login</a>
		</div>
		{% endif %}
	
	

	<div class="social-media">
		<a href="#"> <i class="fab fa-facebook-f"></i></a>
		<a href="#"> <i class="fab fa-twitter"></i></a>
		<a href="#"> <i class="fab fa-instagram"></i></a>
	</div>
	</div>

	<div class="home-img">
		<img src="{% static 'customer.png' %}">
	</div>
</section>
<!-- home section ends -->


<!-- about section -->
<section class="about" id="about">
	<div class="about-img">
		<img src="{% static 'pu.png' %}">
	</div>

	<div class="about-content">
		<h2 class="heading">About Wilder Loans & Investment</h2>
		<h2>Creating an environment for the rich and poor</h2>
		<p>Welcome to Wilder Loans & Investment, your trusted partner in financial growth and stability. At Wilder Loans & Investment, we specialize in providing tailored grants solutions and investment opportunities that empower individuals and businesses to achieve their financial goals.</p>
		<a href="{% url 'work:about' %}" class="btn">Read More</a>
	</div>
</section>
<!-- about section -->

<!-- loans section -->
<section class="loans" id="loans">
	<h2 class="heading">Choose your type of loan</h2>
	<div class="loans-container">
		<div class="loans-box">
			<i class="fas fa-industry"></i>
			<h3>Agricultural Loan</h3>
			<p>Agriculture remains the backbone of our economy, providing food, employment, and income for millions. However, many farmers face challenges such as limited access to resources, outdated farming techniques, and the impacts of climate change. The Sustainable Agricultural Development Initiative aims to address these issues by providing grants to support innovative, sustainable farming practices.
</p>
			<a href="{% url 'work:agric' %}" class="btn">Choose Plan</a>
		</div>

		<div class="loans-box">
			<i class="fas fa-briefcase"></i>
			<h3>Business Loan</h3>
			<p>Small and medium-sized enterprises (SMEs) are crucial to economic development, job creation, and innovation. However, many businesses face significant barriers to growth, such as limited access to capital, technology, and expertise. The Innovative Business Growth and Sustainability Program aims to address these challenges by providing grants to support the expansion and sustainability of SMEs.</p>
			<a href="{% url 'work:business' %}" class="btn">Choose Plan</a>
		</div>



		<div class="loans-box">
			<i class="fas fa-fax"></i>
			<h3>Housing/Assest Loan</h3>
			<p>Access to affordable housing and essential community assets is vital for the well-being and economic stability of individuals and families. However, many communities face a shortage of affordable housing and lack critical infrastructure and resources. The Affordable Housing and Community Assets Development Program aims to address these issues by providing grants to support the development of affordable housing and community assets.</p>
			<a href="{% url 'work:business' %}" class="btn">Choose Plan</a>
		</div>
	</div>
	
</section>
<!-- loans section ends -->





<!-- investment section -->
<section class="loans" id="investment">
	<h2 class="heading">Choose Investment Plan</h2>
	<div class="loans-container">
		<div class="loans-box">
			<i class="fas fa-anchor"></i>
			<h3>Beginners Plan</h3>
			<p>Investing can be a powerful way to grow your wealth and secure your financial future. However, as a beginner, navigating the world of investments can be daunting. The Beginner Investment Plan is designed to provide a straightforward, step-by-step approach to help you start investing with confidence and build a solid foundation for your financial journey</p>
			<a href="{% url 'work:begin' %}" class="btn">Choose Plan</a>
		</div>

		<div class="loans-box">
			<i class="fas fa-bell"></i>
			<h3>Promo Plan</h3>
			<p>Our Promotional Investment Plan is designed to help you take the first step towards financial growth with ease and confidence. We offer a tailored approach to investing that suits beginners and experienced investors alike, providing you with the tools and support needed to achieve your financial goals.</p>
			<a href="{% url 'work:promo' %}" class="btn">Choose Plan</a>
		</div>



		<div class="loans-box">
			<i class="fas fa-archive"></i>
			<h3>Finale Plan</h3>
			<p>The Finale Investment Plan is your gateway to achieving financial independence and long-term wealth accumulation. Designed for both novice and seasoned investors, this plan offers a comprehensive, guided approach to making smart investment decisions. With expert advice, a diversified portfolio, and exclusive promotional benefits, we make investing straightforward and rewarding.</p>
			<a href="{% url 'work:finale' %}" class="btn">Choose Plan</a>
		</div>
	</div>
	
</section>
<!-- investment section ends -->

<!-- testimonies section -->
<section class="testimonies" id="testimonies">
	<img src="{% static 'certificate.png' %}" style="width:100%">
	<h2 class="heading">Users Review</h2>

	<div class="testimonies-container">
		<div class="testimonies-box">
			<img src="{% static 'Ralilia Afrom.png' %}">
			<div class="testimonies-layer">
				<h4>Ralilia Afrom</h4>
				<p>This is so so incredible, i requested for a loan for my agriculture business, my loan was approved with a team of expert to provide me professional advice where needed.</p>
			</div>
		</div>


		<div class="testimonies-box">
			<img src="{% static 'Ahmed Batrus.png' %}">
			<div class="testimonies-layer">
				<h4>Ahmed Batrus</h4>
				<p>This is so so incredible, i requested for a loan for my agriculture business, my loan was approved with a team of expert to provide me professional advice where needed.</p>
			</div>
		</div>



		<div class="testimonies-box">
			<img src="{% static 'Muhammed Hamza.png' %}">
			<div class="testimonies-layer">
				<h4>Muhammed Hamza</h4>
				<p>This is so so incredible, i requested for a loan for my agriculture business, my loan was approved with a team of expert to provide me professional advice where needed.</p>
			</div>
		</div>



		<div class="testimonies-box">
			<img src="{% static 'Andrellia.png' %}">
			<div class="testimonies-layer">
				<h4>Andrellia Halsen</h4>
				<p>This is so so incredible, i requested for a loan for my agriculture business, my loan was approved with a team of expert to provide me professional advice where needed.</p>
			</div>
		</div>


		<div class="testimonies-box">
			<img src="{% static 'Georgia.png' %}">
			<div class="testimonies-layer">
				<h4>Georgia Stephens</h4>
				<p>This is so so incredible, i requested for a loan for my agriculture business, my loan was approved with a team of expert to provide me professional advice where needed.</p>
			</div>
		</div>
	</div>
</section>
<!-- testimonies section ends -->

<!-- contact section ends -->
<section class="contact" id="contact">
	<h2 class="heading">Contact Us</h2>
	<form action="#">
		{% csrf_token %}
		<div class="input-box">
			{{form.first_name}}
			{{form.last_name}}
			<!-- <input type="text" placeholder="Full Name"> -->
			<!-- <input type="email" placeholder="Valid Email Address"> -->
		</div>


		<div class="input-box">
			{{form.phone}}
			{{form.email}}
			<!-- <input type="number" placeholder="Phone Number">
			<input type="text" placeholder="Full Name"> -->
		</div>

			{{form.message}}
		<!-- <textarea name="" id="" cols="30" rows="10" placeholder="Your Message"></textarea> -->
		<input type="submit" name="" value="Send Message" class="btn">
	</form>
</section>
<!-- contact section ends -->


<!-- footer section -->
<footer class="footer">
	<div class="footer-text">
		<p>Creating an environment for the rich and poor</p>
	</div>

	<div class="footer-IconTop">
		<a href="#home"><i class="fa-solid fa-angle-up"></i></a>
	</div>
	
</footer>

<script src="{% static 'js/jquery.js' %}"></script>
<script type="text/javascript">
	let menuIcon  = document.querySelector("#menu-icon");
	let navbar  = document.querySelector(".navbar");

	menuIcon.onclick = () => {
		menuIcon.classList.toggle("fa-xmark")
		navbar.classList.toggle('active')
	}

	let sections = document.querySelectorAll('section');
	let navLinks = document.querySelectorAll('header nav a');

	window.onscroll = () =>{
		sections.forEach(sec=>{
			let top = window.scrollv;
			let offset = secoffsetTop = 150
			let height = sec.offsetHeight;
			let id = sec.getAttribute('id')

			if(top >= offset && top < offset + height){
				navLinks.forEach.apply(links =>{
					links.classList.remove("active");
					document.querySelector("header nav a(href*="+ id + ")").classList.add('active')
				});
			};
		});



		let header = document.querySelector('header');
		header.classList.toggle('sticky', window.scrollv > 100);


		menuIcon.classList.remove('fa-xmark');
		navbar.classList.remove('active');
	}

	setTimeout(fade_out, 2000)
      function fade_out(){
        $(".alert").fadeOut().empty()
      };

      $("#id_first_name").attr("placeholder", "Your First Name..");
      $("#id_last_name").attr("placeholder", "Your Last Name..");
      $("#id_phone").attr("placeholder", "Input your phone number..");
      $("#id_email").attr("placeholder", "Your valid email address..");
	$("#id_message").attr("placeholder", "Type in your email message..");
</script>
</body>

</html>